name: Sync OTA Info

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build releases"]
    types:
      - completed

jobs:
  sync:
    name: Sync OTA Info
    runs-on: ubuntu-latest

    steps:
      - name: Install jq
        run: |
          sudo apt-get install -y jq
          echo "Getting latest workflow run ID..."
          run_id=$(curl -s -H "Authorization: token ${{ secrets.TOKEN_OPPEN321 }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/build-releases.yml/runs?status=success&per_page=1" \
            | jq -r '.workflow_runs[0].id')
          echo "Latest successful run ID: $run_id"
          echo "run_id=$run_id" >> $GITHUB_ENV

      - name: Download all OTA files
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Build releases
          run_id: ${{ env.run_id }}
          name: ota-*
          path: ota_files
          repo: ${{ github.repository }}
          token: ${{ secrets.TOKEN_OPPEN321 }}
          search_artifacts: true
          if_no_artifact_found: warn

      - name: Merge OTA Info
        run: |
          mkdir -p merged
          echo "{}" > merged/ota.json
          
          for file in ota_files/*/fw.json; do
            if [ -f "$file" ]; then
              jq -s '.[0] * .[1]' merged/ota.json "$file" > merged/temp.json
              mv merged/temp.json merged/ota.json
            fi
          done

      - name: Deploy OTA to Gitea
        run: |
          cd merged
          git init
          git config user.name "Gitea Action"
          git config user.email "action@gitea.com"
          git add .
          git commit -m "Update OTA information"
          git branch -M main
          git push -f https://zhao:${{ secrets.GITEA_PASSWORD }}@git.kejizero.online/zhao/OTA.git main
